### PR TITLE
Revert to Rx's Maybe for singleValueEvent as Rx's Single does not has…

### PR DESCRIPTION
**Pull request by gswierczynski**
… onComplete.

Update build tools to 2.3.0.
Update of gradle plugin to 3.3.
Update firebase version to 11.2.2.
Added braces for one line if statements.

### CODE REVIEW

**Comment by FrangSierra** [comment]
Hi @gswierczynski , 

please, give a look to the `tests` cause they are already wrote as `Single`'s if I'm not wrong. If neccessary, change them, execute all of them just to check that it works and update the PR. After that I will merge it.

Thank you for your contribution, is nice to see that people use the library and want to help improving it.

**Comment by gswierczynski** [comment]
All RxFirebaseDatabaseTest tests pass.

There are some failing tests in RxFirebaseAuthTest, but maybe it's just my environment - as I have not touched the RxFirebaseAuth class.

**Comment by gswierczynski** [comment]
Please hold of with the merge, as while investigating https://github.com/FrangSierra/Rx2Firebase/issues/30 I noticed that dataSnapshot.exists check in observeSingleValueEvent as well as in observerValueEvent should be removed.

That will leave both observeSingleValueEvent and observerValueEvent flexible.

When it comes to the convenience methods that accept mapper the:
```java
public static final Predicate<DataSnapshot> DATA_SNAPSHOT_EXISTENCE_PREDICATE = new Predicate<DataSnapshot>() {
      @Override
      public boolean test(@io.reactivex.annotations.NonNull DataSnapshot dataSnapshot) throws Exception {
         return dataSnapshot.exists();
      }
   };
```
should be used before calling map().
Just like it is happening now in:
```java
   public static <T> Maybe<T> observeSingleValueEvent(@NonNull final Query query,
                                                      @NonNull final Function<? super DataSnapshot, ? extends T> mapper) {
      return observeSingleValueEvent(query)
              .filter(DATA_SNAPSHOT_EXISTENCE_PREDICATE)
              .map(mapper);
   }
```

What do you think about it?
That way the behaviour of observeValueEvent and observeSingleValueEvent is not changing compared to previous version but at the same time convenience methods that accept mappers will gracefully ignore non-existing references.

**Comment by gswierczynski** [comment]
To sum up this pull request.
I think it is ready to merge - this is only intended to fix failing build (replace Rx's Single with Maybe, plus libs update).
Removal (assuming that we agree on this) of datansnapshot.exists() from observeValueEvent and adding filtering to with the predicate to convenience methods requires another commit.

**Pull request merged**
